[package]
name = "etrid-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

[lib]
path = "src/lib.rs"

[[bin]]
name = "etrid"
path = "src/main.rs"