//! Autogenerated weights for pallet_token_messenger
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-12-04
//! STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `etrid-benchmark`, CPU: `AMD EPYC 7763 64-Core Processor`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/etrid-node
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_token_messenger
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/pallet-token-messenger/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_token_messenger.
pub trait WeightInfo {
	fn deposit_for_burn() -> Weight;
	fn receive_message() -> Weight;
	fn configure_domain() -> Weight;
	fn remove_domain() -> Weight;
	fn pause_bridge() -> Weight;
	fn unpause_bridge() -> Weight;
}

/// Weights for pallet_token_messenger using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: TokenMessenger IsPaused (r:1 w:0)
	/// Proof: TokenMessenger IsPaused (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: TokenMessenger DomainConfigs (r:1 w:0)
	/// Proof: TokenMessenger DomainConfigs (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	/// Storage: TokenMessenger DailyBurnVolume (r:1 w:1)
	/// Proof: TokenMessenger DailyBurnVolume (max_values: None, max_size: Some(50), added: 2525, mode: MaxEncodedLen)
	/// Storage: TokenMessenger MessageNonce (r:1 w:1)
	/// Proof: TokenMessenger MessageNonce (max_values: None, max_size: Some(16), added: 2491, mode: MaxEncodedLen)
	/// Storage: TokenMessenger OutboundMessages (r:0 w:1)
	/// Proof: TokenMessenger OutboundMessages (max_values: None, max_size: Some(700), added: 3175, mode: MaxEncodedLen)
	/// Storage: TokenMessenger TotalSent (r:1 w:1)
	/// Proof: TokenMessenger TotalSent (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TokenMessenger TotalVolumeSent (r:1 w:1)
	/// Proof: TokenMessenger TotalVolumeSent (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	fn deposit_for_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `450`
		//  Estimated: `3665`
		// Minimum execution time: 85_000_000 picoseconds.
		Weight::from_parts(90_000_000, 3665)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}

	/// Storage: TokenMessenger IsPaused (r:1 w:0)
	/// Proof: TokenMessenger IsPaused (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: TokenMessenger SupportedDomains (r:1 w:0)
	/// Proof: TokenMessenger SupportedDomains (max_values: None, max_size: Some(5), added: 2480, mode: MaxEncodedLen)
	/// Storage: TokenMessenger UsedNonces (r:1 w:1)
	/// Proof: TokenMessenger UsedNonces (max_values: None, max_size: Some(17), added: 2492, mode: MaxEncodedLen)
	/// Storage: TokenMessenger TotalReceived (r:1 w:1)
	/// Proof: TokenMessenger TotalReceived (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TokenMessenger TotalVolumeReceived (r:1 w:1)
	/// Proof: TokenMessenger TotalVolumeReceived (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	fn receive_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `400`
		//  Estimated: `3482`
		// Minimum execution time: 95_000_000 picoseconds.
		Weight::from_parts(100_000_000, 3482)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}

	/// Storage: TokenMessenger DomainConfigs (r:0 w:1)
	/// Proof: TokenMessenger DomainConfigs (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	/// Storage: TokenMessenger SupportedDomains (r:0 w:1)
	/// Proof: TokenMessenger SupportedDomains (max_values: None, max_size: Some(5), added: 2480, mode: MaxEncodedLen)
	fn configure_domain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(18_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: TokenMessenger DomainConfigs (r:0 w:1)
	/// Proof: TokenMessenger DomainConfigs (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	/// Storage: TokenMessenger SupportedDomains (r:0 w:1)
	/// Proof: TokenMessenger SupportedDomains (max_values: None, max_size: Some(5), added: 2480, mode: MaxEncodedLen)
	fn remove_domain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: TokenMessenger IsPaused (r:0 w:1)
	/// Proof: TokenMessenger IsPaused (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	fn pause_bridge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Storage: TokenMessenger IsPaused (r:0 w:1)
	/// Proof: TokenMessenger IsPaused (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	fn unpause_bridge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn deposit_for_burn() -> Weight {
		Weight::from_parts(90_000_000, 3665)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}

	fn receive_message() -> Weight {
		Weight::from_parts(100_000_000, 3482)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}

	fn configure_domain() -> Weight {
		Weight::from_parts(18_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn remove_domain() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn pause_bridge() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn unpause_bridge() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
