version: 2
updates:
  # BSC contracts dependencies
  - package-ecosystem: "npm"
    directory: "/05-multichain/bridge/adapters/bsc"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "etrid-team"
    labels:
      - "dependencies"
      - "bsc"
    commit-message:
      prefix: "chore(bsc)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "etrid-team"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
