[package]
name = "pallet-etrid-staking"
version = "0.1.0"
edition = "2021"
authors = ["Ëtrid Foundation"]
description = "Staking & role assignment pallet for Ëtrid peer-roles system"
license = "Apache-2.0"

[dependencies]
frame-support.workspace = true
frame-system.workspace = true
sp-runtime.workspace = true
sp-std.workspace = true
sp-io.workspace = true
codec.workspace = true
scale-info.workspace = true
log.workspace = true

# Serde for serialization
serde = { workspace = true, features = ["alloc", "derive"], default-features = false }

# Internal Ëtrid dependencies
peer-roles-staking-types = { path = "../types", default-features = false }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-io/std",
    "codec/std",
    "scale-info/std",
    "log/std",
    "serde/std",
    "serde/alloc",
    "peer-roles-staking-types/std",
]
runtime-benchmarks = [
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
]
