[package]
name = "consensus-day-minting-logic"
version = "0.1.0"
edition = "2021"
authors = ["Etrid Foundation"]
license = "Apache-2.0"

[dependencies]
# Substrate / Polkadot SDK Dependencies
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Serialization & Encoding
codec = { workspace = true }
scale-info = { workspace = true }

# Internal Dependencies
consensus-day-proposal-system = { path = "../proposal-system", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-std/std",
    "consensus-day-proposal-system/std",
]
runtime-benchmarks = [
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
]
