[workspace]
members = [
    "runtime/flare-chain",
    "runtime/pbc-runtime",
    "runtime/primitives",
    "node",
    "contracts/consensus",
    "contracts/etwasm-vm",
    "network/detr-p2p",
    "identity/open-did",
    "client/etrid-rust",
    "tools/cli",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/etrid-foundation/etrid"
homepage = "https://etrid.io"

[workspace.dependencies]
# Substrate Core
sp-core = { version = "21.0.0", default-features = false }
sp-runtime = { version = "24.0.0", default-features = false }
sp-std = { version = "8.0.0", default-features = false }
frame-support = { version = "20.0.0", default-features = false }
frame-system = { version = "20.0.0", default-features = false }

# Serialization
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { version = "2.0.0", default-features = false }

# Async
tokio = { version = "1.35", features = ["full"] }

# Common
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
