# Minimal E³20 Workspace - Existing Code Only
[workspace]
resolver = "2"

members = [
    "04-accounts/pallet",
    "08-etwasm-vm/pallet",
    "09-consensus/pallet",
    "10-foundation/governance/pallet",
    "05-multichain/primitives",
    "05-multichain/partition-burst-chains/pbc-runtime",
]

exclude = [
    "_reference",
    "_backup*",
    "target",
    "apps",
]
