[package]
name = "pallet-governance"
version = "0.1.0"
edition = "2021"
authors = ["Ëtrid Foundation"]
description = "Governance pallet for Ëtrid Foundation DAO"
license = "Apache-2.0"

[dependencies]
frame-support.workspace = true
frame-system.workspace = true
sp-runtime.workspace = true
sp-std.workspace = true
codec.workspace = true
scale-info.workspace = true
log.workspace = true

# Internal Ëtrid dependencies - FIXED PATH
pallet-accounts = { path = "../../../04-accounts/pallet", default-features = false }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-std/std",
    "codec/std",
    "scale-info/std",
    "log/std",
    "pallet-accounts/std",
]
runtime-benchmarks = [
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-accounts/runtime-benchmarks",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
    "pallet-accounts/try-runtime",
]
