[package]
name = "etwasm-vm"
version = "0.51.0"
edition = "2021"

[dependencies]
wasmi = "0.51.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "etwasm-vm"
path = "src/main.rs"