[package]
name = "contracts_test_simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
consensus = { path = "../contracts/consensus" }

[[bin]]
name = "test_runner"
path = "main.rs"