[package]
name = "pallet-lightning-channels"
version = "0.1.0"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
sp-runtime = { version = "7.0.0", default-features = false }
sp-std = { version = "5.0.0", default-features = false }
sp-io = { version = "7.0.0", default-features = false }
sp-core = { version = "7.0.0", default-features = false }

[features]
default = ["std"]
std = ["codec/std", "scale-info/std", "frame-support/std", "frame-system/std", "sp-runtime/std", "sp-std/std", "sp-io/std", "sp-core/std"]
