[package]
name = "pallet-lightning-channels"
version = "0.1.0"
edition = "2021"

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true }
sp-core = { workspace = true }

[features]
default = ["std"]
std = ["codec/std", "scale-info/std", "frame-support/std", "frame-system/std", "sp-runtime/std", "sp-std/std", "sp-io/std", "sp-core/std"]
