[package]
name = "etrid-validity-nodes"
version = "0.1.0"
edition = "2021"
authors = ["Ëtrid Foundation"]
license = "Apache-2.0"
description = "Partition-Burst-Chain validators executing consensus on side chains"

[dependencies]
# Workspace internal dependencies
peer-roles-staking-types = { path = "../staking/types", default-features = false }

# Substrate dependencies
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Serialization
codec = { workspace = true }
scale-info = { workspace = true }

# Utilities
log = { workspace = true }

[features]
default = ["std"]

std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-std/std",
    "log/std",
    "peer-roles-staking-types/std",
]

try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
]
