---
# Ëtrid Ember Testnet - Ansible Inventory
# Environment: TESTNET
# Updated: October 24, 2025

all:
  vars:
    # Environment identifier
    environment: "testnet"
    network_name: "ember"

    # Ansible connection settings
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/etrid_ember
    ansible_python_interpreter: /usr/bin/python3

    # Network ports
    p2p_port: 30333
    rpc_port: 9933
    ws_port: 9944
    substrate_metrics_port: 9615
    node_exporter_port: 9100
    prometheus_port: 9090
    grafana_port: 3000
    alertmanager_port: 9093

    # Chain configuration
    chain_name: "ember"
    chain_type: "testnet"
    telemetry_url: "wss://telemetry.polkadot.io/submit/"
    telemetry_enabled: true

    # Substrate node configuration
    pruning: "archive"  # Keep full history for testnet
    db_cache: 2048  # MB
    max_runtime_instances: 8

    # Bootnode (will be populated after first validator is deployed)
    bootnodes: []
    # Example:
    # - "/ip4/X.X.X.X/tcp/30333/p2p/12D3KooW..."

# ============================================
# VALIDATORS (Foundation-operated)
# ============================================
validators:
  hosts:
    validator1:
      ansible_host: 0.0.0.0  # UPDATE: Replace with actual Hetzner IP
      validator_name: "Ember-Validator-1-EU"
      validator_index: 1
      location: "Hetzner FSN1 (Germany)"

    validator2:
      ansible_host: 0.0.0.0  # UPDATE: Replace with actual Hetzner IP
      validator_name: "Ember-Validator-2-EU"
      validator_index: 2
      location: "Hetzner NBG1 (Germany)"

    validator3:
      ansible_host: 0.0.0.0  # UPDATE: Replace with actual Hetzner IP
      validator_name: "Ember-Validator-3-EU"
      validator_index: 3
      location: "Hetzner HEL1 (Finland)"

# ============================================
# BACKUP VALIDATORS (OVH, different region)
# ============================================
backup_validators:
  hosts:
    backup_validator1:
      ansible_host: 0.0.0.0  # UPDATE: Replace with actual OVH IP
      validator_name: "Ember-Backup-Validator-1-US"
      validator_index: 4
      location: "OVH US-East"

    backup_validator2:
      ansible_host: 0.0.0.0  # UPDATE: Replace with actual OVH IP
      validator_name: "Ember-Backup-Validator-2-US"
      validator_index: 5
      location: "OVH US-West"

# ============================================
# RPC NODES (Public endpoints)
# ============================================
rpc_nodes:
  hosts:
    rpc1:
      ansible_host: 0.0.0.0  # UPDATE: Replace with actual Hetzner IP
      rpc_name: "Ember-RPC-1-EU"
      location: "Hetzner FSN1"
      public_endpoint: true

    rpc2:
      ansible_host: 0.0.0.0  # UPDATE: Replace with actual Hetzner IP
      rpc_name: "Ember-RPC-2-EU"
      location: "Hetzner NBG1"
      public_endpoint: true

# ============================================
# MONITORING (Prometheus, Grafana, Alertmanager)
# ============================================
monitoring:
  hosts:
    monitoring1:
      ansible_host: 0.0.0.0  # UPDATE: Replace with actual Hetzner IP
      location: "Hetzner FSN1"

# ============================================
# BLOCK EXPLORER
# ============================================
explorer:
  hosts:
    explorer1:
      ansible_host: 0.0.0.0  # UPDATE: Replace with actual Hetzner IP
      location: "Hetzner FSN1"

# ============================================
# COLLATORS (Partition Burst Chains)
# Uncomment when ready to deploy PBCs
# ============================================
# collators:
#   hosts:
#     btc_collator:
#       ansible_host: 0.0.0.0
#       pbc_chain: "btc-pbc"
#     eth_collator:
#       ansible_host: 0.0.0.0
#       pbc_chain: "eth-pbc"
#     # Add remaining 11 collators as needed
