[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "etrid-sdk"
version = "0.1.0"
description = "Python SDK for Ëtrid Protocol blockchain"
readme = "README.md"
authors = [{ name = "Ëtrid Foundation" }]
license = { text = "Apache-2.0" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.9"
dependencies = [
    "substrate-interface>=1.7.0",
    "websockets>=11.0",
    "pydantic>=2.0",
    "aiohttp>=3.8.0",
]

[project.urls]
Homepage = "https://etrid.io"
Repository = "https://github.com/etrid/etrid-protocol"

[project.optional-dependencies]
dev = ["pytest>=7.0", "pytest-asyncio>=0.21", "black>=23.0", "mypy>=1.0"]
