[package]
name = "pallet-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
frame-support = { version = "14.0.0", default-features = false, features = ["std"] }
frame-system = { version = "14.0.0", default-features = false }
sp-core = { version = "14.0.0", default-features = false }
sp-io = { version = "14.0.0", default-features = false }
sp-runtime = { version = "14.0.0", default-features = false, features = ["std"] }
sp-std = { version = "14.0.0", default-features = false }
parity-scale-codec = { version = "3.0.0", features = ["derive"], default-features = false }
scale-info = { version = "2.1.1", features = ["derive"], default-features = false }
serde = { version = "1.0", features = ["derive"], optional = true }

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-system/std",
  "sp-runtime/std",
  "sp-std/std",
  "sp-core/std",
  "sp-io/std",
  "serde/std",
  "scale-info/std",
  "parity-scale-codec/std"
]
try-runtime = [
  "frame-support/try-runtime",
  "frame-system/try-runtime"
]