[package]
name = "link-pbc-runtime"
version = "0.1.0"
edition = "2021"
authors = ["Ëtrid Foundation"]
description = "Bitcoin Partition Burst Chain runtime for Ëtrid Multichain"
license = "Apache-2.0"

[dependencies]
# PBC Common - Shared runtime code
pbc-common = { path = "../../../pbc-common", default-features = false }

pallet_chainlink_bridge = { package = "chainlink-bridge", path = "../../../../../05-multichain/bridge-protocols/chainlink-bridge", default-features = false }
# Substrate Core - Use workspace dependencies
codec = { workspace = true }
scale-info = { workspace = true }

# FRAME Dependencies
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-executive = { workspace = true }

# Substrate Primitives
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-io = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }
sp-consensus-grandpa = { workspace = true }
sp-consensus-asf = { path = "../../../../../09-consensus/primitives/consensus-asf", default-features = false }
sp-genesis-builder = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-stable2506" }

# FRAME Pallets
pallet-grandpa = { workspace = true }
pallet-sudo = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-insecure-randomness-collective-flip = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-stable2506" }

# Balances - NOT in workspace, so explicit dependency
pallet-balances = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-stable2506" }

# RPC Runtime APIs
frame-system-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-stable2506" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-stable2506" }

# Ëtrid Custom Dependencies
etrid-primitives = { path = "../../../../primitives", default-features = false }
pallet-accounts = { path = "../../../../../04-accounts/pallet", default-features = false }
pallet-consensus = { path = "../../../../../09-consensus/pallet", default-features = false }
pallet-bitcoin-bridge = { path = "../../../../bridge-protocols/bitcoin-bridge", default-features = false }
pallet-lightning-channels = { path = "../../../../lightning-bloc-networks/channel-manager", default-features = false }

[build-dependencies]
# Substrate WASM builder - NOT in workspace, so explicit
substrate-wasm-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-stable2506" }

[features]
default = ["std"]
std = [
    "pbc-common/std",
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "frame-executive/std",
    "sp-api/std",
    "sp-block-builder/std",
    "sp-core/std",
    "sp-inherents/std",
    "sp-io/std",
    "sp-offchain/std",
    "sp-runtime/std",
    "sp-session/std",
    "sp-std/std",
    "sp-transaction-pool/std",
    "sp-version/std",
    "sp-consensus-grandpa/std",
    "sp-consensus-asf/std",
    "sp-genesis-builder/std",
    "pallet-balances/std",
    "pallet-grandpa/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-insecure-randomness-collective-flip/std",
    "frame-system-rpc-runtime-api/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "etrid-primitives/std",
    "pallet-accounts/std",
    "pallet-consensus/std",
    "pallet-bitcoin-bridge/std",
    "pallet-lightning-channels/std",
    "pallet_chainlink_bridge/std",
]
runtime-benchmarks = [
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-accounts/runtime-benchmarks",
    "pallet-consensus/runtime-benchmarks",
]
