[package]
name = "pallet-cardano-bridge"
version = "0.1.0"
edition = "2021"
authors = ["Ëtrid Foundation"]
description = "Cardano Bridge Pallet for Ëtrid"
license = "Apache-2.0"

[dependencies]
# Substrate Core - Use workspace dependencies
codec = { workspace = true }
scale-info = { workspace = true }

# FRAME Dependencies
frame-support = { workspace = true }
frame-system = { workspace = true }

# Substrate Primitives
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
sp-core = { workspace = true }
sp-io = { workspace = true }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-stable2509" }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-std/std",
]
runtime-benchmarks = [
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
]
