//! Pallet Bridge - Auto Generated by Blitzy

#![cfg_attr(not(feature = "std"), no_std)]

use frame_support::{decl_module, decl_event, decl_storage, decl_error, dispatch};
use frame_system::ensure_signed;

pub trait Config: frame_system::Config {
    type Event: From<Event<Self>> + Into<<Self as frame_system::Config>::Event>;
}

decl_storage! {
    trait Store for Module<T: Config> as BridgeModule {
        BridgeCount get(fn bridge_count): u32;
    }
}

decl_event! {
    pub enum Event<T> {
        BridgeInitiated(u32),
    }
}

decl_module! {
    pub struct Module<T: Config> for enum Call where origin: T::Origin {
        fn deposit_event() = default;

        #[weight = 10_000]
        fn initiate_bridge(origin) {
            let _sender = ensure_signed(origin)?;
            let id = <BridgeCount>::get() + 1;
            <BridgeCount>::put(id);
            Self::deposit_event(RawEvent::BridgeInitiated(id));
        }
    }
}
