[dependencies.wasm-project]
default-features = false
features = ["cumulus-pallet-parachain-system"]
package = "frame-storage-access-test-runtime"
path = "/Users/macbook/.cargo/git/checkouts/polkadot-sdk-dee0edd6eefa0594/6fd693e/substrate/utils/frame/storage-access-test-runtime"

[lib]
crate-type = ["cdylib"]
name = "frame_storage_access_test_runtime"

[package]
edition = "2021"
name = "frame-storage-access-test-runtime-blob"
version = "1.0.0"

[profile.dev]
panic = "abort"

[profile.production]
codegen-units = 1
inherits = "release"
lto = "fat"

[profile.release]
lto = "thin"
panic = "abort"

[workspace]
resolver = "2"
