//! Pallet EDSC - Auto-Generated by Blitzy

#![cfg_attr(not(feature = "std"), no_std)]

use frame_support::{decl_module, decl_storage, decl_event, decl_error, dispatch};
use frame_system::ensure_signed;

pub trait Config: frame_system::Config {
    type Event: From<Event<Self>> + Into<<Self as frame_system::Config>::Event>;
}

decl_storage! {
    trait Store for Module<T: Config> as EdscModule {
        TotalSupply get(fn total_supply): u128;
        ReserveBacking get(fn reserve_backing): u128; // Off-chain updated
    }
}
