[package]
name = "block-production"
version = "0.1.0"
edition = "2021"
authors = ["Ëtrid Foundation"]
description = "Block authoring and production for Ëtrid FODDoS ASF consensus"
license = "Apache-2.0"

[dependencies]
# Substrate primitives
sp-core = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }
sp-io = { workspace = true }

# Codec
codec = { workspace = true }
scale-info = { workspace = true }

# Serialization
serde = { workspace = true }

# Logging
log = { workspace = true }

# Internal dependencies
asf-algorithm = { path = "../asf-algorithm", default-features = false }
validator-management = { path = "../validator-management", default-features = false }

# Async runtime (std only)
futures = { version = "0.3.30", optional = true }
tokio = { version = "1.36", features = ["full"], optional = true }

# Error handling
thiserror = { version = "1.0", optional = true }

# Time utilities (std only)
chrono = { version = "0.4", optional = true }

[dev-dependencies]
sp-io = { workspace = true }
sp-core = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[features]
default = ["std"]
std = [
    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",
    "sp-io/std",
    "codec/std",
    "scale-info/std",
    "serde/std",
    "log/std",
    "asf-algorithm/std",
    "validator-management/std",
    "futures",
    "tokio",
    "thiserror",
    "chrono",
]
