version: '3.8'

services:
  # Telemetry Backend (receives data from validators)
  backend:
    image: parity/substrate-telemetry-backend:latest
    container_name: telemetry-backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"  # Internal only, Nginx proxies to this
    environment:
      - RUST_LOG=info
    command: [
      "--listen", "0.0.0.0:8000"
    ]
    networks:
      - telemetry

  # Telemetry Frontend (web UI)
  frontend:
    image: parity/substrate-telemetry-frontend:latest
    container_name: telemetry-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:80"  # Internal only, Nginx proxies to this
    environment:
      - SUBSTRATE_TELEMETRY_URL=wss://telemetry.etrid.org/feed
    networks:
      - telemetry

  # Shard (handles WebSocket connections)
  shard:
    image: parity/substrate-telemetry-shard:latest
    container_name: telemetry-shard
    restart: unless-stopped
    ports:
      - "127.0.0.1:8001:8001"  # Internal only
    environment:
      - RUST_LOG=info
    command: [
      "--listen", "0.0.0.0:8001",
      "--core", "http://backend:8000/shard_submit"
    ]
    depends_on:
      - backend
    networks:
      - telemetry

networks:
  telemetry:
    driver: bridge
