# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
use_modular_headers!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'EtridWallet' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'EtridWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix for React Native 0.76.x modulemap conflict with Xcode 16+
    react_runtime_modulemap_path = "#{Pod::Config.instance.installation_root}/Pods/Headers/Public/ReactCommon/React-RuntimeApple.modulemap"
    if File.exist?(react_runtime_modulemap_path)
      modulemap_content = File.read(react_runtime_modulemap_path)
      modulemap_content.gsub!("module ReactCommon {", "module React_RuntimeApple {")
      File.write(react_runtime_modulemap_path, modulemap_content)
      puts "Fixed React-RuntimeApple.modulemap module name conflict"
    end

    # Fix for React Native 0.79.x react_runtime modulemap conflict with Xcode 16+
    # Remove React-jsitooling.modulemap as it conflicts with React-RuntimeCore in the same directory
    jsitooling_modulemap_symlink = "#{Pod::Config.instance.installation_root}/Pods/Headers/Public/react_runtime/React-jsitooling.modulemap"
    jsitooling_umbrella_symlink = "#{Pod::Config.instance.installation_root}/Pods/Headers/Public/react_runtime/React-jsitooling-umbrella.h"
    if File.exist?(jsitooling_modulemap_symlink)
      File.delete(jsitooling_modulemap_symlink)
      puts "Removed conflicting React-jsitooling.modulemap symlink"
    end
    if File.exist?(jsitooling_umbrella_symlink)
      File.delete(jsitooling_umbrella_symlink)
      puts "Removed conflicting React-jsitooling-umbrella.h symlink"
    end

    # Also fix React-RuntimeCore.modulemap to avoid conflict
    runtime_core_modulemap_path = "#{Pod::Config.instance.installation_root}/Pods/Target Support Files/React-RuntimeCore/React-RuntimeCore.modulemap"
    if File.exist?(runtime_core_modulemap_path)
      modulemap_content = File.read(runtime_core_modulemap_path)
      modulemap_content.gsub!("module react_runtime {", "module React_RuntimeCore {")
      File.write(runtime_core_modulemap_path, modulemap_content)
      puts "Fixed React-RuntimeCore.modulemap module name conflict"
    end
  end
end
