---
# Ëtrid Mainnet - Ansible Inventory
# Environment: MAINNET (PRODUCTION)
# Updated: October 24, 2025

all:
  vars:
    # Environment identifier
    environment: "mainnet"
    network_name: "etrid"

    # Ansible connection settings
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/etrid_mainnet
    ansible_python_interpreter: /usr/bin/python3

    # Network ports
    p2p_port: 30333
    rpc_port: 9933
    ws_port: 9944
    substrate_metrics_port: 9615
    node_exporter_port: 9100
    prometheus_port: 9090
    grafana_port: 3000
    alertmanager_port: 9093

    # Chain configuration
    chain_name: "etrid"
    chain_type: "mainnet"
    telemetry_url: "wss://telemetry.etrid.org/submit/"  # Custom telemetry for mainnet
    telemetry_enabled: true

    # Substrate node configuration
    pruning: "256"  # Pruned nodes for mainnet (except archive)
    db_cache: 4096  # MB (higher for mainnet)
    max_runtime_instances: 16  # More instances for mainnet

    # Bootnode (will be populated after genesis)
    bootnodes: []
    # Mainnet bootnodes will be Foundation-operated and highly available

# ============================================
# FOUNDATION VALIDATORS (Multi-region)
# ============================================
validators:
  hosts:
    # US Region
    validator1:
      ansible_host: 0.0.0.0  # UPDATE: AWS/Hetzner US-East
      validator_name: "Etrid-Foundation-Validator-1-US-East"
      validator_index: 1
      location: "US-East"
      provider: "AWS"

    validator2:
      ansible_host: 0.0.0.0  # UPDATE: AWS/Hetzner US-West
      validator_name: "Etrid-Foundation-Validator-2-US-West"
      validator_index: 2
      location: "US-West"
      provider: "AWS"

    # EU Region
    validator3:
      ansible_host: 0.0.0.0  # UPDATE: Hetzner EU-Central
      validator_name: "Etrid-Foundation-Validator-3-EU-Central"
      validator_index: 3
      location: "EU-Central (Germany)"
      provider: "Hetzner"

    validator4:
      ansible_host: 0.0.0.0  # UPDATE: Hetzner EU-West
      validator_name: "Etrid-Foundation-Validator-4-EU-West"
      validator_index: 4
      location: "EU-West (UK)"
      provider: "Hetzner"

    # Asia-Pacific Region
    validator5:
      ansible_host: 0.0.0.0  # UPDATE: AWS/OVH Asia-Pacific
      validator_name: "Etrid-Foundation-Validator-5-APAC"
      validator_index: 5
      location: "Asia-Pacific (Singapore)"
      provider: "AWS"

    # Latin America Region
    validator6:
      ansible_host: 0.0.0.0  # UPDATE: AWS LatAm
      validator_name: "Etrid-Foundation-Validator-6-LatAm"
      validator_index: 6
      location: "South America (Brazil)"
      provider: "AWS"

    # Additional high-availability validators
    validator7:
      ansible_host: 0.0.0.0
      validator_name: "Etrid-Foundation-Validator-7-EU-North"
      validator_index: 7
      location: "EU-North (Finland)"
      provider: "Hetzner"

    validator8:
      ansible_host: 0.0.0.0
      validator_name: "Etrid-Foundation-Validator-8-Canada"
      validator_index: 8
      location: "North America (Canada)"
      provider: "OVH"

    validator9:
      ansible_host: 0.0.0.0
      validator_name: "Etrid-Foundation-Validator-9-Australia"
      validator_index: 9
      location: "Asia-Pacific (Australia)"
      provider: "AWS"

    validator10:
      ansible_host: 0.0.0.0
      validator_name: "Etrid-Foundation-Validator-10-Japan"
      validator_index: 10
      location: "Asia-Pacific (Japan)"
      provider: "AWS"

# ============================================
# BACKUP VALIDATORS (Hot standby)
# ============================================
backup_validators:
  hosts:
    backup_validator1:
      ansible_host: 0.0.0.0
      validator_name: "Etrid-Backup-Validator-1"
      location: "US-East (Standby)"

    backup_validator2:
      ansible_host: 0.0.0.0
      validator_name: "Etrid-Backup-Validator-2"
      location: "EU-Central (Standby)"

    backup_validator3:
      ansible_host: 0.0.0.0
      validator_name: "Etrid-Backup-Validator-3"
      location: "APAC (Standby)"

# ============================================
# RPC NODES (Multi-region, public endpoints)
# ============================================
rpc_nodes:
  hosts:
    # US Region
    rpc_us_east_1:
      ansible_host: 0.0.0.0
      rpc_name: "Etrid-RPC-US-East-1"
      location: "US-East"
      public_endpoint: true
      region: "us-east"

    rpc_us_east_2:
      ansible_host: 0.0.0.0
      rpc_name: "Etrid-RPC-US-East-2"
      location: "US-East"
      public_endpoint: true
      region: "us-east"

    rpc_us_west_1:
      ansible_host: 0.0.0.0
      rpc_name: "Etrid-RPC-US-West-1"
      location: "US-West"
      public_endpoint: true
      region: "us-west"

    # EU Region
    rpc_eu_central_1:
      ansible_host: 0.0.0.0
      rpc_name: "Etrid-RPC-EU-Central-1"
      location: "EU-Central"
      public_endpoint: true
      region: "eu-central"

    rpc_eu_central_2:
      ansible_host: 0.0.0.0
      rpc_name: "Etrid-RPC-EU-Central-2"
      location: "EU-Central"
      public_endpoint: true
      region: "eu-central"

    rpc_eu_west_1:
      ansible_host: 0.0.0.0
      rpc_name: "Etrid-RPC-EU-West-1"
      location: "EU-West"
      public_endpoint: true
      region: "eu-west"

    # Asia-Pacific Region
    rpc_apac_1:
      ansible_host: 0.0.0.0
      rpc_name: "Etrid-RPC-APAC-1"
      location: "Singapore"
      public_endpoint: true
      region: "apac"

    rpc_apac_2:
      ansible_host: 0.0.0.0
      rpc_name: "Etrid-RPC-APAC-2"
      location: "Japan"
      public_endpoint: true
      region: "apac"

    # Latin America
    rpc_latam_1:
      ansible_host: 0.0.0.0
      rpc_name: "Etrid-RPC-LatAm-1"
      location: "Brazil"
      public_endpoint: true
      region: "latam"

    # Archive RPC (full history)
    rpc_archive_1:
      ansible_host: 0.0.0.0
      rpc_name: "Etrid-Archive-RPC-1"
      location: "US-East"
      public_endpoint: true
      archive_node: true
      pruning: "archive"

# ============================================
# MONITORING (Regional deployment)
# ============================================
monitoring:
  hosts:
    monitoring_primary:
      ansible_host: 0.0.0.0
      location: "US-East"
      role: "primary"

    monitoring_secondary:
      ansible_host: 0.0.0.0
      location: "EU-Central"
      role: "secondary"

# ============================================
# BLOCK EXPLORER
# ============================================
explorer:
  hosts:
    explorer_primary:
      ansible_host: 0.0.0.0
      location: "US-East"

    explorer_secondary:
      ansible_host: 0.0.0.0
      location: "EU-Central"

# ============================================
# COLLATORS (Partition Burst Chains)
# Production deployment
# ============================================
collators:
  hosts:
    btc_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "btc-pbc"
      location: "US-East"

    eth_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "eth-pbc"
      location: "US-East"

    doge_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "doge-pbc"
      location: "EU-Central"

    sol_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "sol-pbc"
      location: "US-West"

    xlm_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "xlm-pbc"
      location: "EU-Central"

    xrp_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "xrp-pbc"
      location: "APAC"

    bnb_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "bnb-pbc"
      location: "APAC"

    trx_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "trx-pbc"
      location: "APAC"

    ada_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "ada-pbc"
      location: "EU-West"

    link_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "link-pbc"
      location: "US-East"

    matic_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "matic-pbc"
      location: "US-West"

    usdt_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "usdt-pbc"
      location: "US-East"

    edsc_collator:
      ansible_host: 0.0.0.0
      pbc_chain: "edsc-pbc"
      location: "EU-Central"
