[package]
name = "etrid-bridge-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.0", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = ["codec/std", "scale-info/std"]
