[package]
name = "pallet-accounts"
version = "0.1.0"
edition = "2021"

[dependencies]
frame-support = { version = "24", default-features = false }
frame-system = { version = "24", default-features = false }
sp-runtime = { version = "24", default-features = false }
sp-std = { version = "24", default-features = false }

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-system/std",
  "sp-runtime/std",
  "sp-std/std"
]