//! Pallet Reputation - Auto Generated by Blitzy

#![cfg_attr(not(feature = "std"), no_std)]

use frame_support::{decl_module, decl_event, decl_storage, decl_error, dispatch};
use frame_system::ensure_signed;

pub trait Config: frame_system::Config {
    type Event: From<Event<Self>> + Into<<Self as frame_system::Config>::Event>;
}

decl_storage! {
    trait Store for Module<T: Config> as ReputationModule {
        ReputationScore get(fn reputation_score): map hasher(blake2_128_concat) u64 => u32;
    }
}
