orchestrator:
  name: "Ëtrid AI Devs Orchestrator"
  version: "1.0.0"
  llm_backend: "claude"  # or "gpt" or "local"

workspace_path: "/workspace"
skills_path: "/app/skills"

agents:
  compiler_ai:
    did: "did:etrid:compiler-01"
    endpoint: "http://localhost:4001/compiler"
    description: "Autonomous compilation and testing agent"
    skills:
      - etrid-compile-build
      - error-debugging
      - workspace-manager
      - integration-test
    priority: "high"
    auto_start: true

  governance_ai:
    did: "did:etrid:governance-01"
    endpoint: "http://localhost:4002/governance"
    description: "Governance orchestration and proposal management"
    skills:
      - proposal-generator
      - vote-simulation
      - committee-rotation
      - consensus-day-orchestrator
      - compliance-dev
      - ethics-dev
      - moderation-dev
      - governance-dev
    priority: "critical"
    auto_start: true

  runtime_ai:
    did: "did:etrid:runtime-01"
    endpoint: "http://localhost:4003/runtime"
    description: "Runtime upgrade and node management"
    skills:
      - runtime-upgrade
      - node-launcher
      - integration-test
    priority: "high"
    auto_start: true

  economics_ai:
    did: "did:etrid:economics-01"
    endpoint: "http://localhost:4004/economics"
    description: "Token economics and reserve monitoring"
    skills:
      - reserve-tracker
      - vmw-simulator
      - bridge-monitor
      - distribution-scheduler
      - edsc-dev
    priority: "medium"
    auto_start: true

  security_ai:
    did: "did:etrid:security-01"
    endpoint: "http://localhost:4005/security"
    description: "Security auditing and threat detection"
    skills:
      - security-hardening
      - bridge-monitor
      - slashing-verifier
      - audit-dev
      - reputation-dev
    priority: "critical"
    auto_start: true

  oracle_ai:
    did: "did:etrid:oracle-01"
    endpoint: "http://localhost:4006/oracle"
    description: "AI-powered oracle with anomaly detection"
    skills:
      - oracle-dev
      - bridge-monitor
    priority: "medium"
    auto_start: true

llm:
  claude:
    api_key: "${ANTHROPIC_API_KEY}"
    model: "claude-sonnet-4"
    max_tokens: 4096
    temperature: 0.7

  gpt:
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-4"
    max_tokens: 4096
    temperature: 0.7

  local:
    endpoint: "${OLLAMA_ENDPOINT}"
    model: "llama2"
    max_tokens: 4096

vectordb:
  type: "qdrant"
  endpoint: "${VECTORDB_URL}"
  collection: "etrid-memory"
  vector_size: 1536  # OpenAI embedding size
  distance: "cosine"

blockchain:
  rpc_endpoint: "${ETRID_WS_URL}"
  chain: "flare"
  network: "ember-testnet"
  polling_interval: 6  # seconds (block time)

notion:
  api_key: "${NOTION_API_KEY}"
  database_id: "${NOTION_DATABASE_ID}"
  sync_interval: 300  # seconds

monitoring:
  prometheus_port: 9090
  grafana_port: 3000
  metrics_enabled: true
  logging_enabled: true

skills:
  execution_timeout: 300  # seconds
  max_concurrent: 5
  retry_attempts: 3
  retry_delay: 5  # seconds
