#!/bin/bash
# Add Lightning-Bloc to all remaining PBC chains
# Generated by Claude Code - November 5, 2025

PBC_BASE="/Users/macbook/Desktop/etrid/05-multichain/partition-burst-chains/pbc-chains"
LIGHTNING_PATH="../../../../../lightning-bloc-networks/channel-manager"

# List of PBCs that need Lightning integration
PBCS=("sc-usdt-pbc" "sol-pbc" "trx-pbc" "xrp-pbc" "xlm-pbc" "matic-pbc" "link-pbc" "doge-pbc" "edsc-pbc")

for PBC in "${PBCS[@]}"; do
    echo "====================================================================="
    echo "Adding Lightning to $PBC"
    echo "====================================================================="

    CARGO_TOML="${PBC_BASE}/${PBC}/runtime/Cargo.toml"

    if [ ! -f "$CARGO_TOML" ]; then
        echo "ERROR: $CARGO_TOML not found!"
        continue
    fi

    # Check if Lightning already added
    if grep -q "pallet-lightning-channels" "$CARGO_TOML"; then
        echo "✅ Lightning already in $PBC Cargo.toml - skipping"
        continue
    fi

    echo "📝 Adding pallet-lightning-channels to $PBC Cargo.toml..."

    # Add dependency before [build-dependencies]
    sed -i.bak '/^\[build-dependencies\]/i \
# Lightning Bloc Integration\
pallet-lightning-channels = { path = "'$LIGHTNING_PATH'", default-features = false }\
' "$CARGO_TOML"

    # Add to std features (find the closing bracket of std features)
    sed -i.bak '/^std = \[/,/^\]/ s/^\]/    "pallet-lightning-channels\/std",\
]/' "$CARGO_TOML"

    echo "✅ Added to $PBC Cargo.toml"
done

echo "====================================================================="
echo "✅ Lightning dependencies added to all PBCs!"
echo "====================================================================="
echo ""
echo "Next steps:"
echo "1. Add Lightning configuration to each runtime's lib.rs"
echo "2. Test compilation with: cargo build -p <pbc-name>-runtime"
