//! Autogenerated weights for pallet_bridge_attestation
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: (placeholder)
//! STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `placeholder`, CPU: `placeholder`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// (placeholder)

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_bridge_attestation.
pub trait WeightInfo {
	fn register_attester() -> Weight;
	fn disable_attester() -> Weight;
	fn enable_attester() -> Weight;
	fn remove_attester() -> Weight;
	fn submit_signature() -> Weight;
	fn verify_attestation() -> Weight;
	fn update_threshold() -> Weight;
	fn pause_attestation() -> Weight;
	fn unpause_attestation() -> Weight;
}

/// Placeholder weights (replace with actual benchmarked weights in production)
impl WeightInfo for () {
	/// Register a new attester
	fn register_attester() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3000))
	}

	/// Disable an attester
	fn disable_attester() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1000))
	}

	/// Enable an attester
	fn enable_attester() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1000))
	}

	/// Remove an attester
	fn remove_attester() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2000))
	}

	/// Submit a signature for verification
	fn submit_signature() -> Weight {
		Weight::from_parts(80_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3000))
	}

	/// Verify an attestation with M signatures
	fn verify_attestation() -> Weight {
		// Base weight + weight per signature verification
		Weight::from_parts(100_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5000))
	}

	/// Update threshold configuration
	fn update_threshold() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1000))
	}

	/// Pause attestation service
	fn pause_attestation() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 100))
	}

	/// Unpause attestation service
	fn unpause_attestation() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 100))
	}
}
