[database]
# Database backend configuration for Ëtrid Protocol
# Optimized for production validator nodes

# Database type (rocksdb is recommended for Substrate)
type = "rocksdb"
path = "chains/flarechain/db"

# Cache configuration
# Adjust based on available RAM:
# - Validator: 2-4GB (cache_size_mb = 2048-4096)
# - Archive: 8-16GB (cache_size_mb = 8192-16384)
# - RPC: 4-8GB (cache_size_mb = 4096-8192)
cache_size_mb = 4096

[database.rocksdb]
# Write buffer settings
# Controls memory used for writing data before flushing to disk
write_buffer_size_mb = 64
max_write_buffer_number = 3
min_write_buffer_number_to_merge = 1

# Block cache for reads
# Improves read performance by caching frequently accessed blocks
block_cache_size_mb = 2048

# Compression settings
# lz4: Fast compression for recent data
# zstd: Better compression ratio for older data (saves ~30% disk space)
compression_type = "lz4"
bottommost_compression_type = "zstd"

# Compaction settings
# Controls background database optimization
max_background_jobs = 4
level0_file_num_compaction_trigger = 4
level0_slowdown_writes_trigger = 20
level0_stop_writes_trigger = 36

# Bloom filters
# Improves read performance by filtering out non-existent keys
bloom_filter_bits_per_key = 10
use_ribbon_filter = true

# Performance tuning
enable_pipelined_write = true
allow_concurrent_memtable_write = true

# Additional optimizations
max_open_files = 10000
keep_log_file_num = 10
log_file_time_to_roll = 0
