[package]
name = "consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "consensus"
path = "lib.rs"

[[bin]]
name = "consensus_main"
path = "main.rs"