//! Autogenerated weights for `pallet_edsc_bridge_token_messenger`
//!
//! This file provides placeholder weights for the EDSC Bridge Token Messenger pallet.
//! In production, proper benchmarks should be run to generate accurate weights.

use frame_support::weights::Weight;
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_edsc_bridge_token_messenger.
pub trait WeightInfo {
    fn burn_edsc_for_external_chain() -> Weight;
    fn receive_and_mint() -> Weight;
    fn configure_domain() -> Weight;
    fn pause_bridge() -> Weight;
    fn unpause_bridge() -> Weight;
}

/// Substrate weight implementation with default values.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn burn_edsc_for_external_chain() -> Weight {
        Weight::from_parts(50_000_000, 0)
    }
    fn receive_and_mint() -> Weight {
        Weight::from_parts(100_000_000, 0)
    }
    fn configure_domain() -> Weight {
        Weight::from_parts(10_000_000, 0)
    }
    fn pause_bridge() -> Weight {
        Weight::from_parts(5_000_000, 0)
    }
    fn unpause_bridge() -> Weight {
        Weight::from_parts(5_000_000, 0)
    }
}

/// Default unit weight implementation.
impl WeightInfo for () {
    fn burn_edsc_for_external_chain() -> Weight {
        Weight::from_parts(50_000_000, 0)
    }
    fn receive_and_mint() -> Weight {
        Weight::from_parts(100_000_000, 0)
    }
    fn configure_domain() -> Weight {
        Weight::from_parts(10_000_000, 0)
    }
    fn pause_bridge() -> Weight {
        Weight::from_parts(5_000_000, 0)
    }
    fn unpause_bridge() -> Weight {
        Weight::from_parts(5_000_000, 0)
    }
}
