[package]
name = "stellar-bridge"
version = "0.1.0"
edition = "2021"
authors = ["Ëtrid Team"]
description = "Stellar (XLM) bridge pallet for Ëtrid Multichain with SEP-24, SDEX, and Soroban support"

[dependencies]
# Substrate Core
codec = { workspace = true }
scale-info = { workspace = true }

# FRAME Dependencies
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }

# Substrate Primitives
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Serialization
serde = { version = "1.0", default-features = false, optional = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking?/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "serde/std",
]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
