# Prometheus Configuration for 21 FlareChain Validators
# Deploy this to: /etc/prometheus/prometheus.yml on your monitoring server

global:
  scrape_interval: 15s        # Scrape metrics every 15 seconds
  evaluation_interval: 15s     # Evaluate rules every 15 seconds
  external_labels:
    cluster: 'flarechain-mainnet'
    monitor: 'etrid-prometheus'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'localhost:9093'  # Uncomment if using Alertmanager

# Scrape configurations
scrape_configs:
  # Job 1: Monitor the monitoring server itself
  - job_name: 'monitoring-server'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'monitoring-server'
          role: 'infrastructure'

  # Job 2: All 21 FlareChain Validators
  - job_name: 'flarechain-validators'
    static_configs:
      # Validator 1: Gizzi (AI Overseer) - Chicago
      - targets: ['64.181.215.19:9615']
        labels:
          instance: 'validator-01-gizzi'
          validator_name: 'Gizzi (AI Overseer)'
          location: 'Chicago'
          role: 'validator'
          bootnode: 'true'

      # Validator 2: EojEdred (Founder)
      - targets: ['<VALIDATOR_02_IP>:9615']
        labels:
          instance: 'validator-02-eojedred'
          validator_name: 'EojEdred (Founder)'
          location: 'TBD'
          role: 'validator'
          bootnode: 'true'

      # Validator 3
      - targets: ['<VALIDATOR_03_IP>:9615']
        labels:
          instance: 'validator-03'
          validator_name: 'validator-3'
          location: 'TBD'
          role: 'validator'
          bootnode: 'true'

      # Validator 4
      - targets: ['<VALIDATOR_04_IP>:9615']
        labels:
          instance: 'validator-04'
          validator_name: 'validator-4'
          location: 'TBD'
          role: 'validator'

      # Validator 5
      - targets: ['<VALIDATOR_05_IP>:9615']
        labels:
          instance: 'validator-05'
          validator_name: 'validator-5'
          location: 'TBD'
          role: 'validator'

      # Validator 6
      - targets: ['<VALIDATOR_06_IP>:9615']
        labels:
          instance: 'validator-06'
          validator_name: 'validator-6'
          location: 'TBD'
          role: 'validator'

      # Validator 7
      - targets: ['<VALIDATOR_07_IP>:9615']
        labels:
          instance: 'validator-07'
          validator_name: 'validator-7'
          location: 'TBD'
          role: 'validator'

      # Validator 8
      - targets: ['<VALIDATOR_08_IP>:9615']
        labels:
          instance: 'validator-08'
          validator_name: 'validator-8'
          location: 'TBD'
          role: 'validator'

      # Validator 9
      - targets: ['<VALIDATOR_09_IP>:9615']
        labels:
          instance: 'validator-09'
          validator_name: 'validator-9'
          location: 'TBD'
          role: 'validator'

      # Validator 10
      - targets: ['<VALIDATOR_10_IP>:9615']
        labels:
          instance: 'validator-10'
          validator_name: 'validator-10'
          location: 'TBD'
          role: 'validator'

      # Validator 11
      - targets: ['<VALIDATOR_11_IP>:9615']
        labels:
          instance: 'validator-11'
          validator_name: 'validator-11'
          location: 'TBD'
          role: 'validator'

      # Validator 12
      - targets: ['<VALIDATOR_12_IP>:9615']
        labels:
          instance: 'validator-12'
          validator_name: 'validator-12'
          location: 'TBD'
          role: 'validator'

      # Validator 13
      - targets: ['<VALIDATOR_13_IP>:9615']
        labels:
          instance: 'validator-13'
          validator_name: 'validator-13'
          location: 'TBD'
          role: 'validator'

      # Validator 14
      - targets: ['<VALIDATOR_14_IP>:9615']
        labels:
          instance: 'validator-14'
          validator_name: 'validator-14'
          location: 'TBD'
          role: 'validator'

      # Validator 15
      - targets: ['<VALIDATOR_15_IP>:9615']
        labels:
          instance: 'validator-15'
          validator_name: 'validator-15'
          location: 'TBD'
          role: 'validator'

      # Validator 16
      - targets: ['<VALIDATOR_16_IP>:9615']
        labels:
          instance: 'validator-16'
          validator_name: 'validator-16'
          location: 'TBD'
          role: 'validator'

      # Validator 17
      - targets: ['<VALIDATOR_17_IP>:9615']
        labels:
          instance: 'validator-17'
          validator_name: 'validator-17'
          location: 'TBD'
          role: 'validator'

      # Validator 18
      - targets: ['<VALIDATOR_18_IP>:9615']
        labels:
          instance: 'validator-18'
          validator_name: 'validator-18'
          location: 'TBD'
          role: 'validator'

      # Validator 19
      - targets: ['<VALIDATOR_19_IP>:9615']
        labels:
          instance: 'validator-19'
          validator_name: 'validator-19'
          location: 'TBD'
          role: 'validator'

      # Validator 20
      - targets: ['<VALIDATOR_20_IP>:9615']
        labels:
          instance: 'validator-20'
          validator_name: 'validator-20'
          location: 'TBD'
          role: 'validator'

      # Validator 21
      - targets: ['<VALIDATOR_21_IP>:9615']
        labels:
          instance: 'validator-21'
          validator_name: 'validator-21'
          location: 'TBD'
          role: 'validator'

  # Job 3: Node Exporters on Validators (system metrics - optional)
  - job_name: 'validator-nodes'
    static_configs:
      - targets:
        - '64.181.215.19:9100'
        # - '<VALIDATOR_02_IP>:9100'
        # ... (add all 21 if you install node_exporter on each)
