name: CI – ASF Finality

on:
  push:
    paths:
      - './Etrid_Phase1_Missing_Repos/asf-finality/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Etrid_Phase1_Missing_Repos/asf-finality

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test --verbose
